import type { TMigration } from "@orphnet/d1-eloquent/cli";
import { Schema } from "@orphnet/d1-eloquent/cli";

// Auto-generated by `d1-eloquent generate`. Review before running `migrate`.
//
// This file is committed verbatim as the feature-12 (schema-diff) showcase.
// The ShowcaseDoc model (src/models/showcase.ts) declares a `tags` column that
// the original create-table migration (…101800) did not have. Running
// `bun run db:generate` diffs the model's declared columns against the schema
// reconstructed from migration history and emits exactly this ALTER migration
// to close the drift. `bun run db:migrate` then applies it.
const migration: TMigration = {
    name: "20260517102400_alter_showcase_docs_add_tags",

    up: (schema: Schema) => {
        schema.table("showcase_docs", (t) => {
            t.addText("tags");
        });
    },

    down: (schema: Schema) => {
        schema.table("showcase_docs", (t) => {
            t.dropColumn("tags");
        });
    },
};

export default migration;
